pipeline {
  agent any

  parameters {
  choice choices: ['TEST', 'QA', 'PROD', 'PRE-pROD'], name: 'ENVIRON'
}

            
    

    stages {
        stage ('BUILD') {
            steps {
                sh 'sleep 2'

            }
        }  
        stage ('TEST') {
            steps {
                sh 'sleep 2'


            }
        } 

        stage ('DEPLOY') {
            steps {
                sh 'sleep 5'
            }
        }   
  


    }
}
